[server]
port = 80

[theme]

# Primary color for interactive elements
primaryColor = '#7393B3'

# Background color for the main content area
backgroundColor = '#333333'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#ffffff'

# Color used for almost all text
textColor = '#D22B2B'

# Font family for all text in the app, except code blocks

font = "serif"